branch-defaults:
  dev:
    environment: staging
  master:
    environment: production
global:
  application_name: phourus
  default_ec2_keyname: aws-eb
  default_platform: 64bit Amazon Linux 2015.03 v1.3.1 running Node.js
  default_region: us-west-2
  profile: eb-cli
  sc: git
