"use strict";
let React = require('react');

let Terms = React.createClass({
  render: function () {
    return (
      <div className="general">
        <h1>Terms & Conditions</h1>
        <strong>Effective: August 1, 2015</strong><br /><br />
        <strong>Acceptance of Terms.</strong>
      This Terms of Service document is an agreement you must accept in order to use Phourus’ Service (as defined below). It is applicable to (a) “Owners” -- this includes Primary Owners who initially set up the Service and other Owners that are granted ownership privileges by the Primary Owner; (b) Administrators – those who manage and run a team, channel, or group (“Administrators”) (Owners and Administrators, collectively “Administrative Users”), and to c) Members – users who are invited to join an existing team that has already been created in the Service by an Administrator (“Members”). The terms “you” and “users” encompass all users, including both Administrative Users and Members. This document describes both your rights and your obligations as part of using the Service. It is important that you read it carefully because you will be legally bound to these terms. Phourus, Inc. (“Phourus” “we” “us”) only provides its Service (as defined below) to you subject to this TOS. By accepting this TOS or by accessing or using the Service, you agree to be bound by this TOS (including the Privacy Policy, which is incorporated here by reference).
  If you are entering into this TOS on behalf of a company or other legal entity, you represent that you have the authority to bind such entity, its Members, its Administrative Users, and its affiliates to this TOS. In that case, the terms “you” or “your” shall also refer to such entity, its Members, its Administrative Users, and its affiliates, as applicable. If you do not have such authority, or if you do not agree with this TOS, you may not use the Service. You acknowledge that this TOS is a contract between you and Phourus, even though it is electronic and is not physically signed by you and Phourus, and it governs your use of the Service.
  If you are accessing the Service in your capacity as a United States government entity, there are special US Government Terms that may apply to you.
  As our business evolves, Phourus may change this TOS. If we make a material change to the TOS, we will provide you with reasonable notice prior to the changes either by emailing the email address associated with your account or by posting a notice on the Site. You can review the most current version of the TOS at any time by visiting this page. The revised terms and conditions will become effective on the date set forth in our notice, and if you use the Service after that date, your use will constitute acceptance of the revised terms and conditions. If any change to this TOS is not acceptable to you, your only remedy is to cancel your account and stop using the Services, which you may do by clicking here or otherwise through the process provided in the Service.
  As part of the registration process, you will identify an Owner’s user name (in the form of an email address) and password for your account. You may use these credentials to invite individuals to become Administrative Users and Members (each with their own password) under your account. The total number of users is limited to the maximum number permitted for your account. You are responsible for maintaining the confidentiality of your login, password, and account and for all activities that occur under your login or account, including the activities of Members.
  All users should be aware that your Administrative Users may have certain rights to access your account and may obtain related information in connection with the Services. The Administrators also set policies regarding your use of various aspects of the Services, including retention settings and the ability to preserve and export all communications in the account. As these rights may vary depending on the account, please see our FAQs for general information about account classifications, and refer to your Administrator if you have questions regarding your particular account such as your account settings. Please also see the Privacy Policy for more information on these topics. Administrators are solely responsible for informing members of the applicable company policies, obtaining any legally required member consent to such policies, and for ensuring that all uses of the Services comply with applicable federal, state and/or international privacy laws, including but not limited to, the Electronic Communications Privacy Act, 18 U.S.C. § 2510 et seq.
  By accessing or using the Services, you affirm that you are at least 18 years of age (or have reached the age of majority if that is not 18 years of age where you live). You represent that you are fully able and competent to enter into and comply with the terms and conditions in this TOS. The Service is not directed to children under 13, so if you are under 13 years of age, you are not permitted to access or use the Services. If we become aware that you are using the Service even though you are under 13, we will deactivate your account.
  If you are a school or teacher in the United States and want your students, who are over 13, to use the Service, including in conjunction with the establishment of a Service account for the school or a group of students at the school, you are responsible for complying with the U.S. Family Educational Rights and Privacy Act (“FERPA”). This means you must notify those students’ parents/guardians of the personally identifiable information you will collect and share with Slack and obtain parental/guardian consent before your students establish accounts or use the Service. When obtaining such consent, you should provide parents/guardians with a copy of our Privacy Policy. You must keep all consents on file and provide them to us if we request them. If you are located outside of the United States, we will rely upon you to obtain any required consent or approval from the parent or guardian of any student covered by similar laws and, as a condition to your and your students’ use of the Service, you will comply with such laws.
  Description of Service.
  The “Service(s)” means (a) Phourus’ communication, posting, archiving and search services and related systems and technologies, as well as the website http://phourus.com, and (b) all software (including the Software, as defined below), applications, data, reports, text, images, and other content made available by or on behalf of Phourus through any of the foregoing. The “Service” does not include Your Data (as defined below) or any software application or service that is provided by you or a third party, which you use in connection with the Service, whether or not Phourus designates them as “official integrations” (each a “Non-Phourus Product”). Any modifications and new features added to the Service are also subject to this TOS. Phourus reserves the right to modify or discontinue the Service (or any Service plan) or any feature or functionality thereof at any time without notice to you. All rights, title and interest in and to the Service and its components (including all intellectual property rights) will remain with and belong exclusively to Phourus.
  Access and Use of the Service.
  You may access and use the Service only for lawful, authorized purposes and you shall not misuse the Service in any manner (as determined by Phourus in its sole discretion). See Section 6 for specific provisions outlining prohibited uses of the Service. Administrative Users shall be responsible for all actions by Members on their team. You shall comply with any codes of conduct, policies, storage limitations, or other notices Phourus provides you or publishes in connection with the Service from time to time, but if any of those policies materially change the TOS, we will provide you with reasonable notice as provided in Section 1.4 above. You shall promptly notify Phourus if you learn of a security breach related to the Service.
  Any software that may be made available by or on behalf of Phourus in connection with the Service, including Phourus’ mobile and desktop applications, (“Software”) contains proprietary and confidential information that is protected by applicable intellectual property and other laws. Subject to the terms and conditions of this TOS, Phourus only grants you a personal, non-sublicensable and non-exclusive license to use the object code of any Software solely in connection with the Service. Any rights not expressly granted herein are reserved.
  Phourus reserves the right to use your name as a reference for marketing or promotional purposes on the Site and in other communication with existing or potential Phourus customers. For example, we might list your company on one of our webpages under lists of Phourus customers. We don’t want to list customers who don’t want to be listed, so you may send an email to feedback@phourus.com stating that you do not wish to be used as a reference.
    Phourus may make available, in its sole discretion, a Phourus Application Programming Interface and related documentation, data, code, and other materials provided with the API (collectively “API”). You undertake use of the API at your own risk, and such use of this API is governed by this TOS and the Phourus API Terms of Service (“API TOS”) located at https://phourus.com/terms-of-service/api. You hereby agree to be bound by those terms, and acknowledge that violation of Phourus’ TOS or Phourus' API TOS is grounds for termination of Your Account.
  Your Data Rights and Related Responsibilities.
  "Your Data" means any data and content you upload, post, transmit or otherwise made available via the Services (which may include data you elect to import from Non-Phourus Products you use). "Your Data" includes messages you send, files you upload, comments you make on files, profile information and anything else you enter or upload into the Service. Phourus will make commercially reasonable efforts to ensure that all facilities used to store and process Your Data meet a high standard for security.
  In order for us to provide the Service to you, we require that you grant us certain rights with respect to Your Data. For example, we need to be able to transmit, store and copy Your Data in order to display it to you and your teammates, to index it so you are able to search it, to make backups to prevent data loss, and so on. Your acceptance of this TOS gives us the permission to do so and grants us any such rights necessary to provide the service to you, only for the purpose of providing the service (and for no other purpose). This permission includes allowing us to use third-party service providers (such as Amazon Web Services) in the operation and administration of the Service and the rights granted to us are extended to these third parties to the degree necessary in order for the Service to be provided.
  If any users send us any feedback or suggestions regarding the Service, you grant Phourus an unlimited, irrevocable, perpetual, free license to use any such feedback or suggestions for any purpose without any obligation to you.
  You are solely responsible for your conduct (including by and between all users), the content of Your Data, and all communications with others while using the Services. We may choose to review Public Content (as defined below) for compliance with our policies and guidelines, but you acknowledge that Phourus has no obligation to monitor any information on the Services. However, Phourus may remove or disable any Public Content at any time for any reason or for no reason at all. For example, if you upload files that do not belong to you and use the “Get Public Link” feature to make these files available publicly, we can delete those files. We are not responsible for the accuracy, appropriateness, or legality of Your Data or any other information you and your users may be able to access using the Services. The Services provide features that allow you and your users to share Your Data and other materials with others or to make it public. Please consider carefully what you allow to be shared or made public.
  Payment.
  To the extent you use a Service plan that is made available for a fee, you will be required to select a payment plan and provide Phourus accurate information regarding your credit card or other payment instrument. You will promptly update your account information with any changes in your payment information. You agree to pay Phourus in accordance with the terms set forth on the Site and this TOS, and you authorize Phourus to bill your payment instrument in advance on a periodic basis in accordance with such terms.
  If you dispute any charges you must let Phourus know within sixty (60) days after the date that Phourus invoices you. All amounts paid are non-refundable and we reserve the right to change our prices in the future. If we increase our prices for your Service plan, we will provide notice of the change on the Site and in email to you at least 30 days before the change is to take effect. Your continued use of the Service after the price change goes into effect constitutes your agreement to pay the changed amount. Phourus may choose to bill you through an invoice, in which case, full payment for invoices issued must be received by the date specified in the invoice. Past due fees are subject to a finance charge of 1.5% per month on any outstanding balance, or the maximum permitted by law, whichever is lower, plus all expenses of collection. You shall be responsible for all taxes associated with Services other than U.S. taxes based on Phourus’ net income.
  Representations and Warranties.
  You represent and warrant to Phourus that (i) you have full power and authority to enter into this TOS; (ii) you own all Your Data or have obtained all permissions, releases, rights or licenses required to engage in your activities (and allow Phourus to perform its obligations) in connection with the Services without obtaining any further releases or consents; and (iii) Your Data and your other activities in connection with the Service, and Slack’s exercise of all rights and license granted by you herein, do not and will not violate, infringe, or misappropriate any third party’s copyright, trademark, right of privacy or publicity, or other personal or proprietary right, nor does Your Data contain any matter that is defamatory, obscene, unlawful, threatening, abusive, tortious, offensive or harassing.

  You also agree not to:

  upload, post, transmit, or otherwise make available any of Your Data that is unlawful, harmful, threatening, abusive, harassing, tortious, defamatory, vulgar, obscene, libelous, invasive of another's privacy, hateful, or racially, ethnically, or otherwise objectionable;
  use the Service to harm minors in any way;
  impersonate any person or entity, including, but not limited to, a Phourus employee, Administrator, Owner, or other Member, or falsely state or otherwise misrepresent your affiliation with a person or entity;
  manipulate identifiers in order to disguise the origin of any of Your Data;
  upload, post, transmit, or otherwise make available any of Your Data that you do not have a right to make available under any law or under contractual or fiduciary relationships (such as inside information, proprietary and confidential information learned or disclosed as part of employment relationships or under nondisclosure agreements);
  upload, post, transmit or otherwise make available any of Your Data in a manner that infringes any patent, trademark, trade secret, copyright or other proprietary rights of any party;
  sublicense, resell, rent, lease, transfer or assign (except as permitted in Section 16) the Service or its use, or offer the Service on a time share basis to any third party;
  use the Service to upload, post, transmit, or otherwise make available any unsolicited or unauthorized advertising, promotional materials, "junk mail," "spam," "chain letters," "pyramid schemes," or any other form of solicitation;
  use the Service to upload, post, transmit, or otherwise make available any software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware;
  disrupt the normal flow of dialogue, or otherwise act in a manner that negatively affects other users' ability to engage in real time exchanges using the Service;
  interfere with or disrupt the Service or servers or networks connected to the Service, or disobey any requirements, procedures, policies or regulations of networks connected to the Service, including using any device or software;
  modify, adapt, or hack the Service, including by using any non-public Slack APIs, or otherwise attempt to gain unauthorized access to the Service or its related systems or networks.
  intentionally or unintentionally violate any applicable local, state, national or international law in connection with your use of the Service, including, but not limited to, any data, privacy, or export control laws, or regulations promulgated by the U.S. Securities and Exchange Commission, any rules of any national or other securities exchange, including, without limitation, the New York Stock Exchange, the American Stock Exchange, or the NASDAQ, and any regulations having the force of law;
  use the Service to provide material support or resources (or to conceal or disguise the nature, location, source, or ownership of material support or resources) to any organization(s) designated by the United States government as a foreign terrorist organization pursuant to section 219 of the Immigration and Nationality Act;
  use the Service to "stalk" or otherwise harass another; and/or
  collect or store personal data about other users in connection with any of the prohibited conduct and activities set forth above.
  You acknowledge that Phourus and its designees shall have the right (but not the obligation) in their sole discretion to pre-screen, refuse, or remove any of Your Data that is available via the Service. For example, we may choose to review publically visible content (“Public Content”) posted using the “Get Public Link” feature or other mechanism for sharing content outside of your non-public channel for compliance with our policies and guidelines. If, for instance, you upload files that do not belong to you and make these files available publicly, we can delete those files. We may also review Your Data transmitted through non-public mechanisms (such as non-public channels within the Service) where we deem appropriate, including for violations of this TOS or in response to a user complaint. Without limiting the foregoing, Phourus and its designees shall have the right to remove any of Your Data that violates the TOS or is otherwise objectionable. You must evaluate, and bear all risks associated with, the use of Your Data, including any reliance on the accuracy, completeness, or usefulness of Your Data.

  You acknowledge, consent and agree that Phourus may access, preserve and disclose your account information and Your Data if required to do so by law or in a good faith belief that such access preservation or disclosure is reasonably necessary to: (i) comply with legal process; (ii) enforce the TOS; (iii) respond to claims that any of Your Data violates the rights of third parties; (iv) respond to your requests for customer service; or (v) protect the rights, property or personal safety of Phourus, its users and the public.

  Term; Termination.
  This TOS will continue in full effect unless and until your account or this TOS is terminated as described herein. Service plans that are paid monthly will automatically renew for additional months, and Service plans that are paid annually will automatically renew for additional years. You have the right to deactivate your account at any time. Only Primary Owners have the ability to deactivate and delete team accounts.
  We reserve the right to deactivate and delete your account (or the access privileges of any Member) and terminate this TOS at any time for any reason, or no reason, with or without notice. Without limiting the foregoing, Phourus may, in its sole discretion, publish policies whereby we delete your account for prolonged inactivity. Upon any termination of this TOS, we will have no obligation to maintain or provide Your Data. If your team’s account is deleted, we will delete or destroy all copies of Your Data in our possession or control, in a reasonably expedient way, unless legally prohibited.
  Please see our Privacy Policy at https://phourus.com/privacy-policy for more information about the choices you have regarding Your Data.
  All accrued rights to payment and the terms of Section 5 and Sections 8 through 20 shall survive termination of this TOS.
  Disclaimer of Warranties.
  The Services may be temporarily unavailable for scheduled maintenance or for unscheduled emergency maintenance, or because of other causes beyond our reasonable control, but Slack shall use reasonable efforts to provide advance notice of any material scheduled service disruption. Further, you understand that Your Data may be transmitted or handled in an unencrypted manner if you choose to use unencrypted gateways to connect to the Service. Additionally, while Phourus takes steps to ensure that information provided to its third party vendors and hosting partners is transmitted using reasonable security measures, it does not guarantee that these transmissions will be encrypted. Accordingly, you acknowledge that you bear sole responsibility for adequate security, protection and backup of Your Data. Phourus will have no liability to you for any unauthorized access or use of any of Your Data, or any corruption, deletion, destruction or loss of any of Your Data.
  THE SERVICE AND ALL RELATED COMPONENTS AND INFORMATION ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS WITHOUT ANY WARRANTIES OF ANY KIND, AND PHOURUS EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, TITLE, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. YOU ACKNOWLEDGE THAT PHOURUS DOES NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, TIMELY, SECURE, ERROR-FREE OR VIRUS-FREE, NOR DOES IT MAKE ANY WARRANTY AS TO THE RESULTS THAT MAY BE OBTAINED FROM USE OF THE SERVICES, AND NO INFORMATION, ADVICE OR SERVICES OBTAINED BY YOU FROM PHOURUS OR THROUGH THE SERVICE SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THIS TOS.
  Limitation of Liability.
  UNDER NO CIRCUMSTANCES AND UNDER NO LEGAL THEORY (WHETHER IN CONTRACT, TORT, OR OTHERWISE) SHALL PHOURUS BE LIABLE TO YOU OR ANY THIRD PARTY FOR (A) ANY INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, CONSEQUENTIAL OR PUNITIVE DAMAGES, INCLUDING LOST PROFITS, LOST SALES OR BUSINESS, LOST DATA, OR (B) FOR ANY AMOUNT IN THE AGGREGATE IN EXCESS OF THE FEES ACTUALLY PAID BY YOU IN THE SIX (6) MONTHS PRECEDING THE EVENT GIVING RISE TO YOUR CLAIM OR, IF NO FEES APPLY, FIVE HUNDRED ($500) U.S. DOLLARS, OR (C) ANY MATTER BEYOND OUR REASONABLE CONTROL. THE PROVISIONS OF THIS SECTION ALLOCATE THE RISKS UNDER THIS TOS BETWEEN THE PARTIES, AND THE PARTIES HAVE RELIED ON THESE LIMITATIONS IN DETERMINING WHETHER TO ENTER INTO THIS TOS.
  Some jurisdictions do not allow the exclusion of implied warranties or limitation of liability for incidental or consequential damages, which means that some of the above limitations may not apply to you. IN THESE JURISDICTIONS, PHOURUS’ LIABILITY WILL BE LIMITED TO THE GREATEST EXTENT PERMITTED BY LAW.
  STATUTE OF LIMITATIONS. Regardless of any statute or law to the contrary or the applicable dispute resolution process, an informal complaint pertaining to any Claim or cause of action arising out of or related to use of the Service or under the TOS must be filed with Phourus within one (1) year after such Claim or cause of action arose or be forever barred. For Claims pursuant to the exceptions identified in Section 10.4, these Claims must be filed with the appropriate court within three (3) years after such claim or cause of action arose or be forever barred.
  NOTICE AND PROCEDURE FOR MAKING CLAIMS OF COPYRIGHT OR INTELLECTUAL PROPERTY INFRINGEMENT

  We respect the intellectual property of others, and we ask our users to do the same. We may, in appropriate circumstances and at its discretion, disable and/or terminate the accounts of users who may be repeat infringers. If you believe that your work has been copied in a way that constitutes copyright infringement, or your intellectual property rights have been otherwise violated, please provide Phourus' Copyright Agent the following information:

  a. an electronic or physical signature of the person authorized to act on behalf of the owner of the copyright or other intellectual property interest;

  b. a description of the copyrighted work or other intellectual property that you claim has been infringed;

  c. a description of where the material that you claim is infringing is located on the site;

  d. your address, telephone number, and email address;

  e. a statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law;

  f. a statement by you, made under penalty of perjury, that the above information in your notice is accurate and that you are the copyright or intellectual property owner or authorized to act on the copyright or intellectual property owner's behalf.

  Phourus' Agent for Notice of claims of copyright or other intellectual property infringement can be reached as follows:

  By mail:
  Copyright Agent
  c/o Phourus, Inc.
  929 Colorado Ave

  Santa Monica, CA 90401


  By email: feedback@phourus.com
  Indemnification.
  You shall defend, indemnify, and hold harmless Phourus from and against any claims, actions or demands, including without limitation reasonable legal and accounting fees, arising or resulting from your breach of this TOS, any of Your Data, or your (and your Members’) use or misuse of the Service. Phourus shall provide notice to you of any such claim, suit or demand. Phourus reserves the right to conduct the exclusive defense and control of any matter that is subject to indemnification under this section. In such case, you agree to cooperate with any reasonable requests assisting Phourus’ defense of such matters.
  Enforceability.
  If any provision of this TOS is found to be unenforceable or invalid, that provision will be limited or eliminated to the minimum extent necessary so that this TOS will otherwise remain in full force and effect and enforceable.
  Integration, Modification, and Authority.
  This TOS is the complete and exclusive statement of the mutual understanding of the parties and supersedes and cancels all previous written and oral agreements, communications and other understandings relating to the subject matter of this TOS. All waivers and modifications to this TOS must be in a writing signed by both parties that expressly by its terms modifies or waives a provision of this TOS, except as otherwise provided herein. No agency, partnership, joint venture, or employment is created as a result of this TOS and you do not have any authority of any kind to bind Phourus in any respect whatsoever.
  Assignment.
  You may not assign this TOS without the prior written consent of Phourus, except, if you are a company or other legal entity, you may assign this TOS in connection with a merger, re-organization or acquisition of all or a substantial portion of your assets by another company, but only upon 30-days prior notice to Phourus. Phourus may assign or transfer this TOS, in whole or in part, without restriction.
  Notices.
  Except as otherwise set forth herein, all notices under this TOS will be in writing and will be deemed to have been duly given when received, if personally delivered; when receipt is electronically confirmed, if transmitted by facsimile or email; the day after it is sent, if sent for next day delivery by recognized overnight delivery service; and upon receipt, if sent by certified or registered mail, return receipt requested.
  Choice of Law and Forum.
  The TOS and the relationship between the parties shall be governed by the laws of the State of California without regard to its conflict of law.
  Waiver and Severability of Terms.
  The failure of Phourus to exercise or enforce any right or provision of the TOS shall not constitute a waiver of such right or provision.
  No Right of Survivorship and Non-Transferability.
  If you are a living person, you agree that your account is non-transferable and your rights to the content within your account terminate upon your death, however the content may be thereafter be available and accessible by Administrative Users.
  Government Users.
  Nothing herein makes Phourus a government contractor. If you are a government user or otherwise accessing or using the Phourus Service in a government capacity, the Amendment to Phourus TOS for Government Users located at https://phourus.com/terms-of-service/government shall apply to you.
      </div>
    );
  }
});

module.exports = Terms;
